CREATE EXTERNAL TABLE [mount].[Facility_SAP_HBI_DW_DLY_FACILITY_SAP] (
    [XFAC_PLANT] NVARCHAR (6) NULL,
    [XFAC_NAME] NVARCHAR (32) NULL,
    [XFAC_NAME2] NVARCHAR (32) NULL,
    [XFAC_ADDR] NVARCHAR (32) NULL,
    [XFAC_CITY] NVARCHAR (27) NULL,
    [XFAC_COUNTRY] NVARCHAR (5) NULL,
    [XFAC_DIVISION] NVARCHAR (4) NULL,
    [XFAC_LBU] NVARCHAR (5) NULL,
    [XFAC_FAC_CDE] NVARCHAR (6) NULL,
    [XFAC_SHPPNT] NVARCHAR (5) NULL,
    [XFAC_TSP] NVARCHAR (28) NULL,
    [FACILITY_TYPE] NVARCHAR (20) NULL
)
    WITH (
    DATA_SOURCE = [ADLStorageGen2SSM],
    LOCATION = N'Master/Facility/SAP_HBI_DW_DLY_FACILITY_SAP/US/Facility_SAP_HBI_DW_DLY_FACILITY_SAP',
    FILE_FORMAT = [TextFileFormat_parquet],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 2
    );

