FORECASTING_SCHEMA = {
    "ITEM_ID": "decimal",
    "STYLE_CD":"nvarchar",
    "COLOR_CD":"nvarchar",
    "SIZE_CD":"nvarchar",
    "ATTRIBUTE_CD":"nvarchar",
    "OPEN_ORDERS_UNITS":"decimal",
    "OPEN_EVENT_UNITS":"decimal",
    "TIL_UNITS":"decimal",
    "SAFETY_STOCK_UNITS":"decimal",
    "CYCLE_STOCK_UNITS":"decimal",
    "LEAD_TIME":"decimal",
    "AMD_UNITS":"decimal",
    "MAXBUILDS_UNITS":"decimal",
    "FORECAST_UNITS":"decimal",
    "HYBRID_FORECAST_UNITS":"decimal",
    "DEMAND_DATE":"date",
    "AS_OF_DATE":"date",
    "CREATE_TIMESTAMP":"date",
    "CREATE_USERID":"nvarchar",
    "DPR_NET_OPEN_ORDERS_UNITS":"decimal",
    "CUSTOMER_SHIP_DATE":"date",
    "DPR_GROSS_OPEN_ORDERS_UNITS":"decimal",
    "GROSS_DPR_DEMAND":"decimal",
    "NET_DPR_DEMAND":"decimal",
    "ORIGINAL_EVENT_UNITS":"decimal",
    "PIPELINE_INVENTORY":"decimal",
    "PLANT_CD":"nvarchar",
    "DC_TIL_UNITS":"decimal",
    "PREVIOUS_TIL_UNITS":"decimal",
    "UPDATE_TIMESTAMP":"date",
    "UPDATE_USERID":"nvarchar",
    "AWD_UNITS": "decimal"
}


MATERIAL_MASTER_SCHEMA = {
    "MANDT":"CLNT",
    "MATNR":"CHAR",
    "ERSDA":"DATS",
    "CREATED_AT_TIME":"TIMS",
    "ERNAM":"CHAR",
    "LAEDA":"DATS",
    "AENAM":"CHAR",
    "VPSTA":"CHAR",
    "MTART":"CHAR",
    "MBRSH":"CHAR",
    "MATKL":"CHAR",
    "BISMT":"CHAR",
    "MEINS":"UNIT",
    "BSTME":"UNIT",
    "VKORG":"CHAR",
    "VTWEG":"CHAR",
    "VERSG":"CHAR",
    "BONUS":"CHAR",
    "PROVG":"CHAR",
    "SKTOF":"CHAR",
    "WERKS":"CHAR",
    "PSTAT":"CHAR",
    "LVORM":"CHAR",
    "BWTTY":"CHAR",
    "VPRSV":"CHAR",
    "VERPR":"CURR",
    "STPRS":"CURR",
    "PEINH":"DEC"
}
